# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.19 is version 41
loaderVersion="[41,)"
# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/"
# If the mods defined in this file should show as separate resource packs
showAsResourcePack=false

[[mods]]
modId="russianmagic"
version="1.0.0.0"
displayName="Russian Magic"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
credits="I'd like to thank my mother and father."
authors="Rik, Regela"
description='''
  Lets you craft dirt into diamonds. This is a traditional mod that has existed for eons. It is ancient. The holy Notch created it. Jeb rainbowfied it. Dinnerbone made it upside down. Etc.
  '''
displayTest="MATCH_VERSION"

[[dependencies.russianmagic]]
modId="forge"
mandatory=true
versionRange="[41,)"
ordering="NONE"
side="BOTH"

[[dependencies.russianmagic]]
modId="minecraft"
mandatory=true
versionRange="[1.19,)"
ordering="NONE"
side="BOTH"